spring:
  application:
    name: transfer_bank
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: 'postgres'
    password: 'root'

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: false
    properties:
      javax:
        persistence:
          schema-generation:
            database:
              action: none
    hibernate:
      ddl-auto: create-drop
      hbm2dll:
        create_namespaces: true
      show_sql: true
      format_sql: true
      connection:
        autocommit: false
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      temp:
        use_jdbc_metadata_defaults:
          false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
    database-change-log-lock-table: bank_databasechangeloglock
    database-change-log-table: bank_databasechangelog



  rabbitmq:
    addresses: localhost:5672

logging:
  file:
    name: logs/banks.log

scheduler:
  interval: 30000

app:
  client_exchange: clientExchange
  client_queue: clientQueue